-- ALTER TABLE products
-- ALTER COLUMN name SET NOT NULL,
-- ALTER COLUMN price SET NOT NULL,
-- ALTER COLUMN description SET NOT NULL,
-- ALTER COLUMN stock SET NOT NULL,
-- ALTER COLUMN image SET NOT NULL;


-- ALTER TABLE products
-- MODIFY COLUMN name VARCHAR(200) NOT NULL,
-- MODIFY COLUMN price FLOAT NOT NULL,
-- MODIFY COLUMN description TEXT NOT NULL,
-- MODIFY COLUMN stock INT NOT NULL,
-- MODIFY COLUMN image VARCHAR(300) NOT NULL;
-- 



--POSTGRES (Adding new auto increamented column )
-- ALTER TABLE products
-- ADD COLUMN id SERIAL PRIMARY KEY;



ALTER TABLE products
ADD COLUMN id INT PRIMARY KEY AUTO_INCREMENT;